# Generated by Django 5.1.6 on 2025-04-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('busiiness', 'ビジネス'), ('lifestyle', '生活'), ('other', 'その他')], max_length=20, verbose_name='カテゴリー')),
            ],
        ),
    ]
