# Generated by Django 5.1.6 on 2025-04-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_category_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル'),
        ),
    ]
