# Generated by Django 5.1.6 on 2025-04-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_review_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='サムネイル'),
        ),
    ]
